//
//  VTypes.h
//  Metrics
//
//  Created by Justin on 2014-12-09.
//  Copyright (c) 2014 Swift. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSUInteger, VStatus)
{
    ER_NO_ERROR = 0,
    ER_BAD_INPUT,
    ER_NO_FIDUCIAL_FOUND,
    ER_CAMERA_TOO_CLOSE,
    ER_CAMERA_TOO_FAR,
    ER_UNABLE_TO_COPY_PTS,
    ER_INVALID_COLOUR_BUCKET,
    ER_REG_FAILED,
    ER_COLOURBAL_FAILED,
    ER_FIDUCIAL_TOO_CLOSE_TO_BORDER,
    ER_COLOURBAL_TOO_EXTREME,
    ER_REFINED_REGION_DISAPPEARED,
    ER_IMAGE_INVALID_FOR_REFINE,
    ER_REGION_TOO_SMALL_FOR_REFINE,
    ER_BAD_REFINE_MASK,
    ER_BAD_SCALES_FOR_EVOLUTION,
    ER_IMAGE_HAS_POOR_FOCUS,
    ER_NO_FIDUCIAL_COLOUR_CANDIDATES,
    ER_NO_FIDUCIAL_BLOB_CANDIDATES,
    ER_FIDUCIAL_AREA_ERROR,
    ER_FIDUCIAL_SHAPE_ERROR,
    ER_FIDUCIAL_INVALID_IMAGE,
};

typedef NS_ENUM(NSUInteger, VFiducialType)
{
	FT_NO_FIDUCIAL = 0,
	FT_BLUE_DOT,
	FT_GREEN_DOT,
	FT_RED_DOT,
	FT_SWIFT_FID,
	FT_RULER_ANALYSIS,
	FT_MANUAL_OVERRIDE
};

typedef NS_ENUM(NSUInteger, VAnalysisType)
{
	AT_NO_TYPE = 0,
	AT_WOUND,
	AT_MOLE,
	AT_MANY_MOLES
};

typedef NS_ENUM(NSUInteger, VPolygonType)
{
	PT_ADD = 0,
	PT_SUBTRACT
};

typedef NS_ENUM(NSUInteger, VUnitsType)
{
	UT_NO_UNITS = 0,
	UT_MM,
	UT_CM,
	UT_M,
	UT_KM,
	UT_IN,
	UT_FT,
	UT_IDEAL_UNITS
};

typedef NS_ENUM(NSUInteger, VColourBucket)
{
	CB_NO_COLOUR = 0,
	CB_RED,
	CB_GREEN,
	CB_BLACK,
	CB_YELLOW,
	CB_BROWN,
	CB_CONFIGURABLE
};

typedef NS_ENUM(NSUInteger, VColorBalanceTransformMethod)
{
	BM_NO_METHOD = 0,
	BM_GRAY_WORLD_RGB,
	BM_GRAY_WORLD_LAB,
	BM_CONTRAST_STRETCH,	// not implemeted
	BM_CONTRAST_SET        // not implemeted
};

typedef NS_ENUM(NSUInteger, VVersionSkipLevel)
{
	VL_MAJOR = 0,
	VL_MINOR = 1,
	VL_PATCH = 2,
	VL_NONE = 3
};

typedef NS_ENUM(NSUInteger, VClipMethod)
{
	CM_NOMETHOD = 0,
	CM_INTERSECTION = 1,
	CM_UNION = 2,
	CM_DIFFERENCE = 3,
	CM_XOR = 4
};

typedef NS_ENUM(NSUInteger, VAutoEnhanceMethod)
{
    AE_NO_METHOD = 0,
    AE_CONTRAST_ENHANCE,
    AE_BRIGHTNESS_ENHANCE,
    AE_BRIGHTNESS_CONTRAST_ENHANCE
};

